services:

  postgres:
    image: postgres:16.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES-USER: postgres
      POSTGRES-PASSWORD: postgres
      POSTGRES_DB: fit1
